import { Events } from '../../core/events.js';
import { InterventionPriority, InterventionStatus } from '../../domain/interventions/constants.js';
import { createId, now } from '../../domain/shared/utils.js';
const DOMAIN_CONTROLLED_CREATE_FIELDS=new Set(['id','status','actualStart','actualEnd','createdAt','updatedAt','operatorId','assignedOperatorIds','teamId','assignedTeamIds','vehicleId']);
const MUTATION_PROTECTED_FIELDS=new Set([...DOMAIN_CONTROLLED_CREATE_FIELDS,'id','createdAt']);
const CREATE_FIELDS=Object.freeze(['clientId','clientSnapshot','address','city','coordinates','date','startTime','estimatedMinutes','type','priority','description','notes','timeMode','flexibleStartTime','flexibleEndTime']);
export const INTERVENTION_TRANSITIONS=Object.freeze({[InterventionStatus.PROGRAMMATO]:Object.freeze([InterventionStatus.IN_CORSO,InterventionStatus.ANNULLATO]),[InterventionStatus.IN_CORSO]:Object.freeze([InterventionStatus.TERMINATO,InterventionStatus.ANNULLATO]),[InterventionStatus.TERMINATO]:Object.freeze([InterventionStatus.RIAPERTO]),[InterventionStatus.RIAPERTO]:Object.freeze([InterventionStatus.IN_CORSO,InterventionStatus.TERMINATO,InterventionStatus.ANNULLATO]),[InterventionStatus.ANNULLATO]:Object.freeze([])});
function assertNoControlledCreateFields(input){const invalid=Object.keys(input).filter(key=>DOMAIN_CONTROLLED_CREATE_FIELDS.has(key));if(invalid.length)throw new TypeError(`Domain-controlled intervention fields: ${invalid.join(', ')}`)}
const allowedCreateData=input=>Object.fromEntries(CREATE_FIELDS.filter(key=>input[key]!==undefined).map(key=>[key,input[key]]));
const uniq=values=>[...new Set((values??[]).filter(Boolean).map(String))];
const sameIds=(a,b)=>{const aa=uniq(a).sort(),bb=uniq(b).sort();return aa.length===bb.length&&aa.every((v,i)=>v===bb[i])};
export class InterventionsService{
 constructor({repository,teamsRepository,operatorsRepository,eventBus,source='interventions-service',clock=now,idFactory=createId}){Object.assign(this,{repository,teamsRepository,operatorsRepository,eventBus,source,clock,idFactory})}
 async #expandOperatorAliases(ids=[]){const base=uniq(ids),out=[...base];for(const id of base){try{const op=await this.operatorsRepository?.getById?.(id);if(op)out.push(op.id,op.cloudUid,op.uid,op.authUid)}catch{}}return uniq(out)}
 async #assignmentData(operatorIds=[],teamIds=[]){const assignedTeamIds=uniq(teamIds),teams=await Promise.all(assignedTeamIds.map(id=>this.teamsRepository?.getById?.(id))),teamOperatorIds=uniq(teams.flatMap(t=>t?.operatorIds??[])),direct=await this.#expandOperatorAliases(operatorIds),fromTeams=await this.#expandOperatorAliases(teamOperatorIds),assignedOperatorIds=uniq([...direct,...fromTeams]);return{assignedTeamIds,assignedOperatorIds,operatorId:uniq(operatorIds)[0]??teamOperatorIds[0]??assignedOperatorIds[0]??null,teamId:assignedTeamIds[0]??null}}
 async #healAssignments(row){const rawOps=uniq([row.operatorId,...(row.assignedOperatorIds??[])]),teamIds=uniq([row.teamId,...(row.assignedTeamIds??[])]),data=await this.#assignmentData(rawOps,teamIds);if(sameIds(row.assignedOperatorIds,data.assignedOperatorIds)&&sameIds(row.assignedTeamIds,data.assignedTeamIds))return row;try{return await this.repository.update(row.id,{operatorId:row.operatorId??data.operatorId,assignedOperatorIds:data.assignedOperatorIds,teamId:row.teamId??data.teamId,assignedTeamIds:data.assignedTeamIds,updatedAt:this.clock()})}catch{return row}}
 async createIntervention(input={}){assertNoControlledCreateFields(input);const timestamp=this.clock();return this.repository.create({...allowedCreateData(input),id:this.idFactory(),priority:input.priority??InterventionPriority.NORMALE,status:InterventionStatus.PROGRAMMATO,assignedOperatorIds:[],assignedTeamIds:[],actualStart:null,actualEnd:null,createdAt:timestamp,updatedAt:timestamp})}
 async createOfficeIntervention(input={}, {operatorIds=[],teamIds=[],vehicleId=''}={}){assertNoControlledCreateFields(input);const assignment=await this.#assignmentData(operatorIds,teamIds),timestamp=this.clock(),id=this.idFactory();const value=await this.repository.create({...allowedCreateData(input),id,priority:input.priority??InterventionPriority.NORMALE,status:InterventionStatus.PROGRAMMATO,...assignment,vehicleId:vehicleId||null,actualStart:null,actualEnd:null,createdAt:timestamp,updatedAt:timestamp});this.eventBus?.emit(Events.INTERVENTION_CREATED,{entityId:id,source:this.source,timestamp});this.eventBus?.emit(Events.INTERVENTION_ASSIGNMENT_CHANGED,{entityId:id,source:this.source,timestamp,changes:{operatorId:value.operatorId,assignedOperatorIds:value.assignedOperatorIds,teamId:value.teamId,assignedTeamIds:value.assignedTeamIds,vehicleId:value.vehicleId}});return value}
 async updateIntervention(id,patch){const invalid=Object.keys(patch).filter(key=>MUTATION_PROTECTED_FIELDS.has(key));if(invalid.length)throw new TypeError(`Protected intervention fields: ${invalid.join(', ')}`);return this.repository.update(id,{...patch,updatedAt:this.clock()})}
 async saveOfficeIntervention(id,{patch={},operatorIds=[],teamIds=[],vehicleId=''}={}){const current=await this.repository.getById(id);if(!current)throw new Error(`Missing intervention: ${id}`);const invalid=Object.keys(patch).filter(key=>MUTATION_PROTECTED_FIELDS.has(key));if(invalid.length)throw new TypeError(`Protected intervention fields: ${invalid.join(', ')}`);const assignment=await this.#assignmentData(operatorIds,teamIds),timestamp=this.clock();const value=await this.repository.update(id,{...patch,...assignment,vehicleId:vehicleId||null,updatedAt:timestamp});this.eventBus?.emit(Events.INTERVENTION_UPDATED,{entityId:id,source:this.source,timestamp});this.eventBus?.emit(Events.INTERVENTION_ASSIGNMENT_CHANGED,{entityId:id,source:this.source,timestamp,changes:{operatorId:value.operatorId,assignedOperatorIds:value.assignedOperatorIds,teamId:value.teamId,assignedTeamIds:value.assignedTeamIds,vehicleId:value.vehicleId}});return value}
 async removeIntervention(id){const existing=await this.repository.getById(id);if(!existing)throw new Error(`Missing intervention: ${id}`);const removed=await this.repository.remove(id);this.eventBus?.emit(Events.INTERVENTION_DELETED,{entityId:id,source:this.source,timestamp:this.clock()});return removed}
 assignOperator(id,operatorId){return this.#assignment(id,{operatorId,assignedOperatorIds:operatorId?[operatorId]:[]})}
 async assignOperators(id,assignedOperatorIds){const ids=uniq(assignedOperatorIds),expanded=await this.#expandOperatorAliases(ids);return this.#assignment(id,{operatorId:ids[0]??expanded[0]??null,assignedOperatorIds:expanded})}
 async assignTeam(id,teamId){if(!teamId)return this.#assignment(id,{teamId:null,assignedTeamIds:[]});const data=await this.#assignmentData([], [teamId]),current=await this.repository.getById(id),operators=uniq([...(current?.assignedOperatorIds??[]),...data.assignedOperatorIds]);return this.#assignment(id,{teamId,assignedTeamIds:[teamId],operatorId:current?.operatorId??data.operatorId??operators[0]??null,assignedOperatorIds:operators})}
 async assignTeams(id,assignedTeamIds){const ids=uniq(assignedTeamIds),data=await this.#assignmentData([],ids),current=await this.repository.getById(id),operators=uniq([...(current?.assignedOperatorIds??[]),...data.assignedOperatorIds]);return this.#assignment(id,{teamId:ids[0]??null,assignedTeamIds:ids,operatorId:current?.operatorId??data.operatorId??operators[0]??null,assignedOperatorIds:operators})}
 assignVehicle(id,vehicleId){return this.#assignment(id,{vehicleId:vehicleId||null})}
 async #assignment(id,patch){const value=await this.repository.update(id,{...patch,updatedAt:this.clock()});this.eventBus?.emit(Events.INTERVENTION_ASSIGNMENT_CHANGED,{entityId:id,source:this.source,timestamp:this.clock(),changes:patch});return value}
 async changeStatus(id,status,extra={},event=Events.INTERVENTION_STATUS_CHANGED){const previous=await this.repository.getById(id);if(!previous)throw new Error(`Missing intervention: ${id}`);if(!INTERVENTION_TRANSITIONS[previous.status]?.includes(status))throw new TypeError(`Invalid intervention transition: ${previous.status} -> ${status}`);const timestamp=this.clock(),value=await this.repository.update(id,{status,...extra,updatedAt:timestamp}),payload={entityId:id,previousStatus:previous.status,status,source:this.source,timestamp};this.eventBus?.emit(Events.INTERVENTION_STATUS_CHANGED,payload);if(event!==Events.INTERVENTION_STATUS_CHANGED)this.eventBus?.emit(event,payload);return value}
 async startIntervention(id){const value=await this.repository.getById(id);if(!value)throw new Error(`Missing intervention: ${id}`);return this.changeStatus(id,InterventionStatus.IN_CORSO,{actualStart:value.actualStart??this.clock()},Events.INTERVENTION_STARTED)}
 completeIntervention(id){return this.changeStatus(id,InterventionStatus.TERMINATO,{actualEnd:this.clock()},Events.INTERVENTION_COMPLETED)} reopenIntervention(id){return this.changeStatus(id,InterventionStatus.RIAPERTO,{actualEnd:null},Events.INTERVENTION_REOPENED)} getIntervention(id){return this.repository.getById(id)}
 async listInterventions(){const rows=await this.repository.list();return Promise.all(rows.map(row=>this.#healAssignments(row)))}
 async listForOperator(operatorId,teamIds=[],aliases=[]){const ids=uniq([operatorId,...aliases]);const directRows=[];for(const id of ids){try{const rows=this.repository.queryByOperator?await this.repository.queryByOperator(id):(await this.repository.list()).filter(x=>x.operatorId===id||x.assignedOperatorIds?.includes(id));directRows.push(...rows)}catch{}}const teamRows=(await Promise.all(uniq(teamIds).map(id=>this.repository.queryByTeam?this.repository.queryByTeam(id):Promise.resolve([])))).flat();let all=[...directRows,...teamRows];try{const fallback=await this.repository.list();const t=uniq(teamIds);all.push(...fallback.filter(x=>ids.includes(String(x.operatorId??''))||(x.assignedOperatorIds??[]).some(id=>ids.includes(String(id)))||t.includes(String(x.teamId??''))||(x.assignedTeamIds??[]).some(id=>t.includes(String(id)))))}catch{}return [...new Map(all.map(row=>[String(row.id),row])).values()]}
}
export const protectedInterventionFields=Object.freeze([...MUTATION_PROTECTED_FIELDS]);export const controlledInterventionCreateFields=Object.freeze([...DOMAIN_CONTROLLED_CREATE_FIELDS]);
