import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const root = new URL('../../../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const [feature, view, model, repository] = await Promise.all([read('src/features/fleet/fleet.feature.js'), read('src/features/fleet/fleet.view.js'), read('src/features/fleet/fleet.model.js'), read('src/services/repositories/vehicles-repository.js')]);
assert.doesNotMatch(feature, /firebase|features\/(?!fleet)/i);
assert.doesNotMatch(feature, /\b(?:window|sfVehicles|renderDashboard|refreshDashboard|DashboardFeature)\b/);
assert.doesNotMatch(view, /repository|firebase/i);
assert.doesNotMatch(model, /\b(?:document|window|localStorage|querySelector|innerHTML)\b/);
assert.doesNotMatch(repository, /\b(?:document|window|HTMLElement|innerHTML)\b/);
console.log('Fleet architectural contracts passed');
