const seedJobs = [
  {id:1001, client:'Condominio Belvedere', address:'Via Roma 24, Sarnico', phone:'+39 333 1234567', issue:'Intasamento scarico garage', time:'10:30', status:'urgent', priority:'Emergenza', operator:'Marco', vehicle:'Autobotte 01', notes:'Chiamare amministratore 10 minuti prima dell’arrivo.', history:['13/03/2026 – Pulizia pozzetto garage','22/09/2025 – Videoispezione condotta'], permanent:'Pozzetto principale dietro il garage. Accesso autobotte dal cancello secondario.'},
  {id:1002, client:'Ristorante Lago', address:'Lungolago Garibaldi 8, Sarnico', phone:'+39 333 4445566', issue:'Pulizia degrassatore', time:'08:00', status:'done', priority:'Normale', operator:'Luca', vehicle:'Autobotte 02', notes:'Accesso da retro cucina.', history:['11/01/2026 – Pulizia degrassatore'], permanent:'Ingresso stretto, preferibile mezzo compatto.'},
  {id:1003, client:'Residence Sole', address:'Via Predore 15, Sarnico', phone:'+39 333 7711223', issue:'Lavaggio tubazione', time:'14:00', status:'planned', priority:'Normale', operator:'Marco', vehicle:'Autobotte 01', notes:'Referente presente dalle 13:45.', history:[], permanent:'Necessari almeno 30 m di tubo.'},
  {id:1004, client:'Bianchi Carlo', address:'Via Vittorio Veneto 4, Paratico', phone:'+39 333 9080706', issue:'Svuotamento fossa biologica', time:'11:15', status:'unassigned', priority:'Urgente', operator:'', vehicle:'', notes:'Cliente disponibile fino alle 13:00.', history:['08/08/2025 – Svuotamento fossa'], permanent:''},
];

const state = {
  role: localStorage.getItem('sf_role') || null,
  operator: localStorage.getItem('sf_operator') || 'Marco',
  jobs: JSON.parse(localStorage.getItem('sf_jobs') || 'null') || seedJobs,
  currentJob: null,
  startedAt: null,
  transcript: '',
  report: ''
};

function save(){ localStorage.setItem('sf_jobs', JSON.stringify(state.jobs)); }
function el(html){ const t=document.createElement('template'); t.innerHTML=html.trim(); return t.content.firstChild; }
function statusLabel(s){ return ({urgent:'Urgente',progress:'In corso',planned:'Programmato',done:'Completato',unassigned:'Da assegnare'})[s]||s; }
function formatTime(sec){ const m=Math.floor(sec/60).toString().padStart(2,'0'); const s=(sec%60).toString().padStart(2,'0'); return `00:${m}:${s}`; }

function render(){ const app=document.getElementById('app'); app.innerHTML=''; if(!state.role) return renderLogin(app); state.role==='office'?renderOffice(app):renderOperator(app); }

function renderLogin(app){
  app.append(el(`<div class="login-wrap"><div class="login-card"><div class="pill">BETA v0.1</div><h1>Spurgo <span style="color:#0f766e">Flow</span></h1><p class="meta">Prototipo dimostrativo per la gestione digitale degli interventi di spurgo.</p><div class="role-grid"><button class="role" id="officeRole"><strong>🏢 Ufficio</strong><br><span class="meta">Agenda, assegnazioni, clienti e rapportini.</span></button><button class="role" id="operatorRole"><strong>🚛 Operatore</strong><br><span class="meta">Interventi, foto, relazione e chiusura.</span></button></div></div></div>`));
  document.getElementById('officeRole').onclick=()=>{state.role='office';localStorage.setItem('sf_role','office');render();};
  document.getElementById('operatorRole').onclick=()=>{state.role='operator';localStorage.setItem('sf_role','operator');render();};
}

function topbar(){ return el(`<div class="topbar"><div class="brand">SPURGO <span>FLOW</span></div><div class="top-actions"><button class="btn btn-secondary" id="switchRole">Cambia area</button></div></div>`); }
function wireTopbar(){ document.getElementById('switchRole').onclick=()=>{localStorage.removeItem('sf_role');state.role=null;render();}; }

function renderOffice(app){
  app.append(topbar());
  const c=el(`<main class="container"><div class="hero"><div><h1>Dashboard ufficio</h1><p>Martedì 11 agosto 2026 · Demo azienda spurghi</p></div><button class="btn btn-primary" id="newJob">+ Nuovo intervento</button></div><div class="grid kpis" id="kpis"></div><div class="grid two" style="margin-top:18px"><section class="card"><div class="section-title"><h2>Interventi di oggi</h2><span class="pill">${state.jobs.length} totali</span></div><div id="jobList"></div></section><section class="card"><div class="section-title"><h2>Agenda operatori</h2></div><div id="agenda"></div></section></div><div class="section-title"><h2>Clienti e memoria tecnica</h2></div><div class="grid three" id="clients"></div></main>`);
  app.append(c); wireTopbar();
  const counts={unassigned:0,planned:0,progress:0,done:0,urgent:0}; state.jobs.forEach(j=>counts[j.status]++);
  document.getElementById('kpis').innerHTML=[['Interventi oggi',state.jobs.length],['Da assegnare',counts.unassigned],['Programm./Urgenti',counts.planned+counts.urgent],['In corso',counts.progress],['Completati',counts.done]].map(x=>`<div class="card kpi"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');
  document.getElementById('jobList').innerHTML=state.jobs.map(j=>`<div class="job"><div class="status-bar status-${j.status}"></div><div><div class="pill">${statusLabel(j.status)}</div><h3>${j.client}</h3><div class="meta">${j.time} · ${j.address}<br>${j.issue}${j.operator?` · Operatore: ${j.operator}`:''}</div></div><button class="btn btn-secondary" onclick="openOfficeJob(${j.id})">Apri</button></div>`).join('');
  const ops=['Marco','Luca']; document.getElementById('agenda').innerHTML=ops.map(o=>`<div class="history-item"><strong>${o}</strong><div class="meta">${state.jobs.filter(j=>j.operator===o).map(j=>`${j.time} – ${j.client}`).join('<br>')||'Nessun intervento'}</div></div>`).join('');
  const grouped=[...new Map(state.jobs.map(j=>[j.client,j])).values()]; document.getElementById('clients').innerHTML=grouped.slice(0,6).map(j=>`<div class="card"><strong>${j.client}</strong><div class="meta">${j.address}</div><p class="meta">${j.permanent||'Nessuna informazione permanente inserita.'}</p><button class="btn btn-secondary" onclick="openClient('${j.client.replace(/'/g,"\\'")}')">Storico</button></div>`).join('');
  document.getElementById('newJob').onclick=renderNewJob;
}

window.openOfficeJob=(id)=>{ const j=state.jobs.find(x=>x.id===id); const app=document.getElementById('app'); app.innerHTML=''; app.append(topbar()); app.append(el(`<main class="container"><button class="btn btn-secondary" onclick="render()">← Dashboard</button><div class="section-title"><h2>${j.client}</h2><span class="pill">${statusLabel(j.status)}</span></div><div class="grid two"><section class="card"><h3>Intervento #${j.id}</h3><p><strong>${j.issue}</strong></p><div class="meta">${j.address}<br>${j.time} · ${j.priority}<br>Operatore: ${j.operator||'Da assegnare'}<br>Mezzo: ${j.vehicle||'—'}</div><div class="section-title"><h2>Note ufficio</h2></div><p>${j.notes||'—'}</p><div class="section-title"><h2>Memoria tecnica</h2></div><p>${j.permanent||'—'}</p></section><section class="card"><h3>Stato operativo</h3><p class="meta">Per la demo puoi assegnare rapidamente l’intervento.</p><div class="field"><label>Operatore</label><select id="assignOp"><option value="">Da assegnare</option><option>Marco</option><option>Luca</option></select></div><div class="field" style="margin-top:10px"><label>Mezzo</label><select id="assignVehicle"><option value="">—</option><option>Autobotte 01</option><option>Autobotte 02</option></select></div><button class="btn btn-primary btn-block" style="margin-top:14px" id="saveAssign">Salva assegnazione</button><div class="section-title"><h2>Storico</h2></div>${j.history.length?j.history.map(h=>`<div class="history-item">${h}</div>`).join(''):'<div class="empty">Nessun precedente</div>'}</section></div></main>`)); wireTopbar(); document.getElementById('assignOp').value=j.operator;document.getElementById('assignVehicle').value=j.vehicle; document.getElementById('saveAssign').onclick=()=>{j.operator=document.getElementById('assignOp').value;j.vehicle=document.getElementById('assignVehicle').value;j.status=j.operator?'planned':'unassigned';save();openOfficeJob(j.id);}; };
window.openClient=(name)=>{ const jobs=state.jobs.filter(j=>j.client===name); const j=jobs[0]; alert(`${name}\n\nStorico interventi demo: ${j.history.length + jobs.length}\n\nMemoria tecnica:\n${j.permanent||'Nessuna nota'}`); };

function renderNewJob(){ const app=document.getElementById('app'); app.innerHTML=''; app.append(topbar()); app.append(el(`<main class="container"><button class="btn btn-secondary" onclick="render()">← Dashboard</button><div class="section-title"><h2>Nuovo intervento</h2></div><form class="card form-grid" id="newJobForm"><div class="field"><label>Cliente</label><input id="client" required></div><div class="field"><label>Telefono</label><input id="phone"></div><div class="field span-2"><label>Indirizzo</label><input id="address" required></div><div class="field"><label>Tipologia</label><select id="issue"><option>Spurgo</option><option>Disotturazione</option><option>Pulizia fossa biologica</option><option>Lavaggio tubazioni</option><option>Videoispezione</option><option>Svuotamento</option><option>Sopralluogo</option><option>Altro</option></select></div><div class="field"><label>Ora</label><input id="time" type="time" value="09:00"></div><div class="field"><label>Priorità</label><select id="priority"><option>Normale</option><option>Urgente</option><option>Emergenza</option></select></div><div class="field"><label>Operatore</label><select id="operator"><option value="">Da assegnare</option><option>Marco</option><option>Luca</option></select></div><div class="field span-2"><label>Descrizione / note</label><textarea id="notes"></textarea></div><div class="span-2"><button class="btn btn-primary btn-block btn-large">Salva e assegna</button></div></form></main>`)); wireTopbar(); document.getElementById('newJobForm').onsubmit=(e)=>{e.preventDefault(); const op=document.getElementById('operator').value; state.jobs.push({id:Date.now(),client:client.value,address:address.value,phone:phone.value,issue:issue.value,time:time.value,status:op?'planned':'unassigned',priority:priority.value,operator:op,vehicle:'',notes:notes.value,history:[],permanent:''});save();render();}; }

function renderOperator(app){
  const jobs=state.jobs.filter(j=>j.operator===state.operator && j.status!=='done');
  app.append(el(`<div class="mobile-shell"><div class="mobile-header"><div class="pill" style="background:#134e4a;color:white">OPERATORE</div><h1>Buongiorno ${state.operator}</h1><div>${jobs.length} interventi assegnati oggi</div></div><div class="mobile-content"><div class="section-title"><h2>I tuoi interventi</h2><button class="btn btn-secondary" id="changeRole">Cambia area</button></div><div id="operatorJobs"></div></div><div class="bottom-nav"><button class="btn btn-secondary" onclick="render()">Oggi</button><button class="btn btn-secondary" onclick="alert('Funzione sopralluogo predisposta per la prossima beta')">Sopralluogo</button><button class="btn btn-secondary" onclick="alert('Storico cliente disponibile dalle schede intervento')">Storico</button></div></div>`));
  document.getElementById('changeRole').onclick=()=>{localStorage.removeItem('sf_role');state.role=null;render();};
  document.getElementById('operatorJobs').innerHTML=jobs.length?jobs.map(j=>`<div class="mobile-job"><div class="pill">${statusLabel(j.status)}</div><h3>${j.client}</h3><div class="meta">${j.time} · ${j.address}<br>${j.issue}</div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="openOperatorJob(${j.id})">Apri intervento</button></div>`).join(''):'<div class="empty">Nessun intervento assegnato</div>';
}

window.openOperatorJob=(id)=>{ const j=state.jobs.find(x=>x.id===id); state.currentJob=j; const app=document.getElementById('app'); app.innerHTML=''; app.append(el(`<div class="mobile-shell"><div class="mobile-header"><button class="btn btn-secondary" onclick="render()">← Oggi</button><h1 style="margin-top:14px">${j.client}</h1><div>${j.address}</div></div><div class="mobile-content"><div class="mobile-actions"><a class="btn btn-secondary" style="text-align:center;text-decoration:none" href="https://maps.apple.com/?q=${encodeURIComponent(j.address)}">🧭 Naviga</a><a class="btn btn-secondary" style="text-align:center;text-decoration:none" href="tel:${j.phone}">📞 Chiama</a></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Richiesta cliente</h2></div><p><strong>${j.issue}</strong></p><p class="meta">${j.notes||'Nessuna nota ufficio.'}</p><div class="section-title"><h2>Memoria tecnica</h2></div><div class="note">${j.permanent||'Nessuna informazione permanente disponibile.'}</div><div class="section-title"><h2>Storico</h2></div>${j.history.length?j.history.map(h=>`<div class="history-item">${h}</div>`).join(''):'<div class="empty">Nessun precedente</div>'}</div><button class="btn btn-success btn-block btn-large" style="margin-top:14px" id="startJob">INIZIA INTERVENTO</button></div></div>`));
  document.getElementById('startJob').onclick=()=>startJob(j);
};

function startJob(j){ j.status='progress'; state.startedAt=Date.now(); save(); renderWorking(j); }
function renderWorking(j){ const app=document.getElementById('app'); app.innerHTML=''; app.append(el(`<div class="mobile-shell"><div class="mobile-header"><div class="pill" style="background:#7c2d12;color:white">INTERVENTO IN CORSO</div><h1>${j.client}</h1><div class="timer" id="timer">00:00:00</div></div><div class="mobile-content"><div class="mobile-actions"><button class="action-tile" id="photoBtn">📷<br>FOTO</button><button class="action-tile" id="voiceBtn">🎙️<br>RELAZIONE</button><button class="action-tile" id="activityBtn">🛠️<br>ATTIVITÀ</button><button class="action-tile" id="anomalyBtn">⚠️<br>ANOMALIA</button></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Relazione operatore</h2></div><textarea id="transcript" style="width:100%;min-height:130px;border:1px solid var(--line);border-radius:12px;padding:12px" placeholder="Detta o scrivi qui cosa è stato fatto...">${state.transcript}</textarea><button class="btn btn-primary btn-block" style="margin-top:10px" id="aiReport">Genera relazione professionale</button><div id="reportBox" style="margin-top:12px"></div></div><button class="btn btn-danger btn-block btn-large" style="margin-top:14px" id="endJob">TERMINA INTERVENTO</button></div></div>`));
  const timer=document.getElementById('timer'); const iv=setInterval(()=>{ if(!document.body.contains(timer)) return clearInterval(iv); timer.textContent=formatTime(Math.floor((Date.now()-state.startedAt)/1000));},1000);
  document.getElementById('photoBtn').onclick=()=>alert('Beta demo: foto classificabili come PRIMA / DURANTE / DOPO / ANOMALIA.');
  document.getElementById('activityBtn').onclick=()=>alert('Beta demo: Spurgo, Aspirazione, Lavaggio alta pressione, Disotturazione, Videoispezione, Pulizia pozzetti.');
  document.getElementById('anomalyBtn').onclick=()=>{ const a=prompt('Descrivi l’anomalia rilevata:'); if(a) state.transcript += `\nAnomalia rilevata: ${a}`; document.getElementById('transcript').value=state.transcript; };
  document.getElementById('voiceBtn').onclick=()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR) return alert('Dettatura vocale non supportata da questo browser. Puoi usare la dettatura della tastiera.'); const r=new SR(); r.lang='it-IT'; r.interimResults=false; r.onresult=e=>{const t=e.results[0][0].transcript; state.transcript=(document.getElementById('transcript').value+' '+t).trim();document.getElementById('transcript').value=state.transcript;}; r.start(); };
  document.getElementById('aiReport').onclick=()=>{ const t=document.getElementById('transcript').value.trim(); state.transcript=t; state.report=t?`<strong>Situazione e attività eseguite</strong><br>${t.replace(/\n/g,'<br>')}<br><br><strong>Esito</strong><br>Intervento registrato e documentato. Eventuali anomalie sono state segnalate per successiva valutazione dell’ufficio.`:'Inserisci prima una breve descrizione dell’intervento.'; document.getElementById('reportBox').innerHTML=`<div class="note">${state.report}</div>`; };
  document.getElementById('endJob').onclick=()=>closeJob(j);
}

function closeJob(j){ const dur=Math.max(1,Math.round((Date.now()-state.startedAt)/60000)); const app=document.getElementById('app'); app.innerHTML=''; app.append(el(`<div class="mobile-shell"><div class="mobile-header"><h1>Chiusura intervento</h1><div>${j.client}</div></div><div class="mobile-content"><div class="card"><p><strong>Durata:</strong> ${dur} min</p><p><strong>Operatore:</strong> ${state.operator}</p><p><strong>Attività:</strong> ${j.issue}</p><div class="section-title"><h2>Relazione</h2></div><div class="note">${state.report||state.transcript||'Nessuna relazione inserita.'}</div><div class="field" style="margin-top:14px"><label>Nome firmatario</label><input id="signer" placeholder="Es. Mario Rossi"></div><div class="field" style="margin-top:10px"><label>Firma cliente</label><div style="height:110px;border:2px dashed var(--line);border-radius:14px;display:grid;place-items:center;color:var(--muted)">Area firma demo</div></div></div><button class="btn btn-success btn-block btn-large" style="margin-top:14px" id="confirmClose">CHIUDI INTERVENTO</button></div></div>`));
  document.getElementById('confirmClose').onclick=()=>{j.status='done'; j.history.unshift(`11/08/2026 – ${j.issue}`); save(); state.transcript='';state.report='';alert('Intervento chiuso. Rapportino demo archiviato e disponibile all’ufficio.');render();};
}

render();
