import { dashboardFeature } from './dashboard/index.js';
import { clientsFeature } from './clients/index.js';
import { fleetFeature } from './fleet/index.js';
import { peopleFeature } from './people/index.js';
import { interventionsFeature } from './interventions/index.js';
import { agendaFeature } from './agenda/index.js';
import { controlRoomFeature } from './control-room/index.js';
import { messagesFeature } from './messages/index.js';
import { reportsFeature } from './reports/index.js';
import { statisticsFeature } from './statistics/index.js';
import { operatorFeature } from './operator/index.js';
export const features = Object.freeze({ dashboard: dashboardFeature, clients: clientsFeature, fleet: fleetFeature, people: peopleFeature, interventions: interventionsFeature, agenda: agendaFeature, 'control-room': controlRoomFeature, messages: messagesFeature, reports: reportsFeature, statistics: statisticsFeature, operator: operatorFeature });
