import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const url = process.env.SMOKE_URL ?? 'http://127.0.0.1:4173/spurgo_flow_v8/';
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH });
const page = await browser.newPage();
const fatalErrors = [];
page.on('pageerror', (error) => fatalErrors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') fatalErrors.push(message.text()); });
await page.goto(url, { waitUntil: 'networkidle' });
await page.locator('#app').waitFor();
const visibleText = (await page.locator('#app').innerText()).trim();
assert.ok((await page.locator('body').innerText()).trim(), 'document.body must not be empty');
assert.ok(visibleText, '#app must contain visible text after bootstrap');
assert.match(visibleText, /COMPLETE OPERATIONAL SUITE/);
assert.match(visibleText, /v8\.0\.0-beta\.1/);
await page.getByRole('button', { name: 'Clienti' }).click();
await page.locator('[data-feature="clients"]').waitFor();
assert.match(await page.locator('#app').innerText(), /Clienti/);
await page.getByRole('button', { name: 'Flotta' }).click();
await page.locator('[data-feature="fleet"]').waitFor();
assert.match(await page.locator('#app').innerText(), /MEZZI & FLOTTA/);
await page.getByRole('button', { name: '+ NUOVO MEZZO' }).click();
await page.locator('[name="plate"]').fill('ab 123 cd');
await page.getByRole('button', { name: 'SALVA' }).click();
await page.getByText('AB 123 CD').waitFor();
await mkdir('artifacts', { recursive: true });
await page.screenshot({ path: 'artifacts/spurgo-flow-v8-beta1-fleet.png', fullPage: true });
for (const route of ['Operatori','Interventi','Agenda','Control Room','Messaggi','Rapportini','Statistiche','App operatore']) { await page.getByRole('button',{name:route,exact:true}).click(); assert.ok((await page.locator('#app').innerText()).trim(), `${route} must not be blank`); }
await page.reload({ waitUntil: 'networkidle' });
await page.locator('[data-feature="dashboard"]').waitFor();
assert.ok(await page.evaluate(() => navigator.serviceWorker.controller !== null), 'service worker must control the refreshed GitHub Pages path');
assert.ok((await page.evaluate(() => caches.keys())).includes('spurgoflow-v8-0.0-beta.1-complete-suite'), 'beta.1 service-worker cache must exist');
assert.deepEqual(fatalErrors, []);
await page.screenshot({ path: 'artifacts/spurgo-flow-v8-beta1.png', fullPage: true });
await browser.close();
console.log(`Browser smoke passed: ${url}`);
