import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const url = process.env.SMOKE_URL ?? 'http://127.0.0.1:4173/spurgo_flow_v8/';
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH });
const page = await browser.newPage();
const fatalErrors = [];
page.on('pageerror', (error) => fatalErrors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') fatalErrors.push(message.text()); });
await page.goto(url, { waitUntil: 'networkidle' });
await page.locator('#app').waitFor();
const visibleText = (await page.locator('#app').innerText()).trim();
assert.ok((await page.locator('body').innerText()).trim(), 'document.body must not be empty');
assert.ok(visibleText, '#app must contain visible text after bootstrap');
assert.match(visibleText, /Foundation v8 avviata correttamente/);
assert.match(visibleText, /v8\.0\.0-alpha\.1/);
await page.getByRole('button', { name: 'Clienti' }).click();
await page.locator('[data-feature="clients"]').waitFor();
assert.match(await page.locator('#app').innerText(), /Clienti/);
await page.reload({ waitUntil: 'networkidle' });
await page.locator('[data-feature="dashboard"]').waitFor();
assert.ok(await page.evaluate(() => navigator.serviceWorker.controller !== null), 'service worker must control the refreshed GitHub Pages path');
assert.ok((await page.evaluate(() => caches.keys())).includes('spurgoflow-v8-0.0-alpha.1-hotfix1'), 'alpha.2 service-worker cache must exist');
assert.deepEqual(fatalErrors, []);
await mkdir('artifacts', { recursive: true });
await page.screenshot({ path: 'artifacts/spurgo-flow-v8-alpha2.png', fullPage: true });
await browser.close();
console.log(`Browser smoke passed: ${url}`);
