import { shell,loading,esc } from '../../shared/ui/operational.js';
let root,ctx,busy=false,item=null;
const selectedId=()=>sessionStorage.getItem('spurgo:selected-intervention');
const option=(id,label,selected=false)=>`<option value="${esc(id)}" ${selected?'selected':''}>${esc(label)}</option>`;
async function render(){
  const id=selectedId();
  if(!id){root.innerHTML=shell('Intervento','<section class="ops-card"><p>Nessun intervento selezionato.</p><button data-route="interventions">Torna agli interventi</button></section>');return;}
  const [current,operators,teams,vehicles]=await Promise.all([ctx.services.interventions.getIntervention(id),ctx.services.operators.listOperators(),ctx.services.teams.listTeams(),ctx.services.vehicles.listVehicles()]);
  if(!current){root.innerHTML=shell('Intervento','<section class="ops-card"><p>Intervento non trovato.</p><button data-route="interventions">Torna agli interventi</button></section>');return;}
  item=current;
  const assignedOps=new Set(current.assignedOperatorIds??[]),assignedTeams=new Set(current.assignedTeamIds??[]);
  root.innerHTML=shell('Scheda intervento',`<section class="ops-card"><div class="table-title"><div><h2>${esc(current.clientSnapshot?.name||'Intervento')}</h2><small>${esc(current.id)}</small></div><button data-route="interventions" class="ghost">← Elenco interventi</button></div><form id="intervention-detail-form" class="ops-form"><label>Cliente<input value="${esc(current.clientSnapshot?.name||'')}" disabled></label><label>Indirizzo<input name="address" value="${esc(current.address||'')}" required></label><label>Città<input name="city" value="${esc(current.city||'')}"></label><label>Data<input type="date" name="date" value="${esc(current.date||'')}" required></label><label>Ora<input type="time" name="startTime" value="${esc(current.startTime||'')}" required></label><label>Durata stimata (min)<input type="number" name="estimatedMinutes" min="1" value="${Number(current.estimatedMinutes)||60}" required></label><label>Tipologia<input name="type" value="${esc(current.type||'')}" required></label><label>Priorità<select name="priority"><option ${current.priority==='NORMALE'?'selected':''}>NORMALE</option><option ${current.priority==='URGENTE'?'selected':''}>URGENTE</option></select></label><label>Operatori<select multiple name="operatorIds">${operators.filter(x=>x.active||assignedOps.has(x.id)).map(o=>option(o.id,o.name,assignedOps.has(o.id))).join('')}</select></label><label>Squadre<select multiple name="teamIds">${teams.filter(x=>x.active||assignedTeams.has(x.id)).map(t=>option(t.id,t.name,assignedTeams.has(t.id))).join('')}</select></label><label>Mezzo<select name="vehicleId"><option value="">Nessuno</option>${vehicles.filter(x=>x.active||x.id===current.vehicleId).map(v=>option(v.id,v.plate||v.name||v.id,v.id===current.vehicleId)).join('')}</select></label><label>Note<textarea name="notes">${esc(current.notes||'')}</textarea></label><div class="actions"><button class="primary" type="submit">Salva modifiche</button><button type="button" data-action="reload">Annulla modifiche</button></div><output data-save-status></output></form></section>`);
}
async function submit(event){if(event.target.id!=='intervention-detail-form')return;event.preventDefault();if(busy)return;busy=true;const form=event.target,submitter=event.submitter;submitter.disabled=true;const out=form.querySelector('[data-save-status]');try{const fd=new FormData(form);await ctx.services.interventions.updateIntervention(item.id,{address:String(fd.get('address')||''),city:String(fd.get('city')||''),date:String(fd.get('date')||''),startTime:String(fd.get('startTime')||''),estimatedMinutes:Number(fd.get('estimatedMinutes')),type:String(fd.get('type')||''),priority:String(fd.get('priority')||'NORMALE'),notes:String(fd.get('notes')||'')});await ctx.services.interventions.assignOperators(item.id,fd.getAll('operatorIds'));await ctx.services.interventions.assignTeams(item.id,fd.getAll('teamIds'));await ctx.services.interventions.assignVehicle(item.id,String(fd.get('vehicleId')||''));if(out)out.textContent='Modifiche salvate.';await render();}catch(error){if(out)out.textContent=error?.message||'Salvataggio non riuscito.';}finally{busy=false;submitter.disabled=false;}}
function click(event){if(event.target.closest?.('[data-action="reload"]'))render();}
export const interventionDetailFeature=Object.freeze({id:'intervention-detail',async mount(container,context){root=container;ctx=context;root.innerHTML=loading('Scheda intervento');root.addEventListener('submit',submit);root.addEventListener('click',click);await render();},unmount(){root?.removeEventListener('submit',submit);root?.removeEventListener('click',click);root=ctx=undefined;item=null;busy=false;}});
