'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const cloud=fs.readFileSync(path.join(__dirname,'..','firebase-sync.js'),'utf8');

assert.strictEqual((html.match(/function finishOperatorIntervention\s*\(/g)||[]).length,1,'una sola funzione di chiusura');
assert.strictEqual((html.match(/>TERMINA INTERVENTO<\/button>/g)||[]).length,1,'un solo pulsante termina');
assert(!html.includes('TERMINA E GENERA RAPPORTINO'));
const finish=html.slice(html.indexOf('async function finishOperatorIntervention'),html.indexOf('\nfunction startJob'));
for(const token of ["String(selectedJob.id)","sfOfficeInterventions.find", "status:'Terminato'",'actualEnd=now.toISOString()','localStorage.setItem','await window.SFCloud.saveIntervention(current)','renderAllOfficeV6()','syncOperatorJobs()'])assert(finish.includes(token),token);
assert(finish.indexOf("alert('Intervento chiuso")>finish.indexOf('await window.SFCloud.saveIntervention'));
assert(cloud.includes('async function saveIntervention(record)'));
assert(cloud.includes("setDoc(doc(db,'interventions',String(record.id))"));
const agenda=html.slice(html.indexOf("let operatorAgendaView='day'"),html.indexOf('function backToOperatorJobs'));
for(const token of ["assignedToOperator(i,id)","status!=='Annullato'",'agenda-timeline','agenda-week-grid',"onclick=\"openOperatorJob",'OGGI','GIORNO','SETTIMANA',"i.status==='Terminato'?'finished'"])assert(agenda.includes(token),token);
assert(html.includes("sessionStorage.setItem('sf_operator_agenda_view','day')"));
assert(!html.includes("source.status='Riaperto'"),'aprire il rapportino terminato non deve riaprire lo stato');
assert(html.includes("current.status='Riaperto'"),'riapertura esplicita preservata');
console.log('v6.1.23.5: agenda personale e chiusura persistente verificate');
