'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const firebase=fs.readFileSync(path.join(__dirname,'..','firebase-sync.js'),'utf8');
for(const token of ['normalizeReportData','operatorSignature','customerSignature','operatorSignedAt','customerSignedAt',"toDataURL('image/png')",'modalHasInk','Firma non acquisita.'])assert(html.includes(token),token);
assert(html.includes("el('firmaOperatore')?.dataset.signature||old.operatorSignature||''"));
assert(html.includes("el('firmaCliente')?.dataset.signature||old.customerSignature||''"));
for(const field of ['relation','activities','anomalies','materials','quantities','photos','location','notes'])assert(html.includes(field),field);
assert(html.includes('function buildReportViewModel(i)'));
assert(html.includes('function openReportPreview(interventionId)'));
assert(html.includes('function renderReport(vm)'));
assert(html.includes('filter(i=>hasReportData(i))'));
assert(html.includes("String(x.id)===String(interventionId)"));
assert(html.includes('alt="Firma operatore"'));
assert(html.includes('alt="Firma cliente"'));
assert(html.includes('buildReportPdfBlob'));
assert(html.includes('renderReport(buildReportViewModel(selectedJob))'));
assert(firebase.includes("await setDoc(doc(db,'interventions',String(record.id)),clean(record),{merge:true})"));
assert(firebase.includes("if(Array.isArray(value))return value.map(clean)"));
const original={id:'INT-9',reportData:{operatorSignature:'op',customerSignature:'cl',photos:{prima:'photo'}}};
const reopened={...original,status:'Riaperto',reportData:{...original.reportData,relation:'aggiornata'}};
assert.strictEqual(reopened.id,original.id);assert.strictEqual(reopened.reportData.operatorSignature,'op');assert.strictEqual(reopened.reportData.customerSignature,'cl');assert.strictEqual(reopened.reportData.photos.prima,'photo');
console.log('v6.1.23.9 report end-to-end hotfix verified');
