const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const clock = value => `${String(Math.floor(Math.max(0, value) / 60) % 24).padStart(2, '0')}:${String(Math.round(Math.max(0, value)) % 60).padStart(2, '0')}`;
const labels = { warning: 'ATTENZIONE', delay: 'RITARDO', critical: 'CRITICO', ok: 'OK' };

export function renderControlRoom(container, model, { message = '', error = '' } = {}) {
  const statusById = Object.fromEntries(model.statuses.map(status => [status.resourceId, status]));
  const resources = model.timeline.map(({ resource }) => { const status = statusById[resource.id]; return `<div class="sf-control-room-resource"><strong>${esc(resource.name)}</strong><span class="sf-control-room-state ${esc(status.severity)}">${esc(labels[status.severity])}</span><small>${esc(status.state)} · disponibile ${clock(status.availableAt)}</small></div>`; }).join('');
  const tracks = model.timeline.map(({ resource, rows }) => `<div class="sf-control-room-track" data-resource-id="${esc(resource.id)}">${rows.map(row => `${row.travelWidth ? `<span class="sf-control-room-travel" style="left:${row.travelLeft}px;width:${row.travelWidth}px">${row.travelMinutes} min</span>` : ''}${row.marginWidth ? `<span class="sf-control-room-margin" style="left:${Math.max(0, row.left - row.marginWidth)}px;width:${row.marginWidth}px"></span>` : ''}<button class="sf-control-room-job ${esc(row.severity)}" data-intervention-id="${esc(row.job.id)}" style="left:${row.left}px;width:${Math.max(48, row.width)}px"><b>${clock(row.start)} ${esc(row.job.client || row.job.clientName || 'Intervento')}</b><small>${row.durationFallback ? '~ stima tecnica' : `${row.durationMinutes} min`}${row.delayMinutes ? ` · +${row.delayMinutes} min` : ''}</small></button>`).join('')}</div>`).join('');
  const issues = model.criticalities.map(issue => `<article class="sf-control-room-criticality ${esc(issue.severity)}"><b>${esc(labels[issue.severity])} · ${esc(issue.resourceName)}</b><small>${issue.delayMinutes ? `Ritardo ${issue.delayMinutes} min` : `Margine ${issue.marginMinutes} min`}${issue.overlap ? ' · sovrapposizione' : ''}</small>${['delay', 'critical'].includes(issue.severity) ? `<button data-action="alternatives" data-intervention-id="${esc(issue.interventionId)}">Trova alternativa</button>` : ''}</article>`).join('');
  container.innerHTML = `<div class="sf-control-room"><div class="sf-control-room-toolbar"><h1>Control Room</h1><input type="date" data-role="date" value="${esc(model.date)}"><button data-action="today">Oggi</button><button data-action="refresh">Aggiorna ora</button></div>${model.degraded ? '<div class="sf-control-room-degraded">Planning temporaneamente non disponibile</div>' : ''}<div class="sf-control-room-message">${esc(message)}</div>${error ? `<div class="sf-control-room-error">${esc(error)}</div>` : ''}<div class="sf-control-room-grid"><section><h3>Risorse</h3>${resources}</section><section class="sf-control-room-timeline"><h3>Timeline dinamica</h3><div class="sf-control-room-scroll">${tracks}</div></section><section><h3>Criticità & suggerimenti</h3>${issues || '<p>Nessuna criticità: pianificazione regolare.</p>'}</section></div><div id="controlMap" class="sf-control-room-map" data-role="map" aria-label="Mappa territoriale"></div></div>`;
}

export function renderAlternatives(container, suggestion) {
  const host = container.querySelector('.sf-control-room-message');
  if (!host) return;
  host.innerHTML = suggestion?.alternatives?.length ? suggestion.alternatives.map(item => `<div class="sf-control-room-suggestion"><b>${esc(item.resourceName)}</b> · arrivo ${clock(item.arrival)} · viaggio ${item.travelMinutes} min<button data-action="assign" data-intervention-id="${esc(suggestion.interventionId)}" data-resource-id="${esc(item.resourceId)}">Riassegna</button></div>`).join('') : 'Nessuna alternativa migliorativa disponibile.';
}
