import { filterInterventions, todayKey } from './interventions.model.js';
import { readInterventionForm } from './interventions.form.js';
import { validateIntervention } from './interventions.validators.js';
import { renderInterventions } from './interventions.view.js';
export class InterventionsFeature { id='interventions'; #container;#context;#rows=[];#lookups={clients:[],operators:[],teams:[],vehicles:[]};#filters={date:todayKey(),query:'',status:'',operatorId:''};#form;#saving=false;#error='';#errors={};
 async mount(container,context={}){if(!container)throw new TypeError('Interventions container is required');this.unmount();this.#container=container;this.#context=context;container.addEventListener('input',this.#input);container.addEventListener('change',this.#input);container.addEventListener('click',this.#click);container.addEventListener('submit',this.#submit);try{await this.refresh()}catch(e){this.#fail(e)}}
 unmount(){this.#container?.removeEventListener('input',this.#input);this.#container?.removeEventListener('change',this.#input);this.#container?.removeEventListener('click',this.#click);this.#container?.removeEventListener('submit',this.#submit);this.#container=undefined;this.#form=undefined;this.#saving=false}
 async refresh(){const r=this.#context.repositories;[this.#rows,this.#lookups.clients,this.#lookups.operators,this.#lookups.teams,this.#lookups.vehicles]=await Promise.all([this.#context.services.interventions.listInterventions(),r.clients.list(),r.operators.list(),r.teams.list(),r.vehicles.list()]);this.#render()}
 #input=e=>{const key=e.target?.dataset?.filter;if(key){this.#filters[key]=e.target.value;this.#render()}};
 #click=e=>{const b=e.target?.closest?.('[data-action]');if(!b)return;const action=b.dataset.action,id=b.closest('[data-intervention-id]')?.dataset.interventionId;if(action==='new')this.#open();if(action==='edit')this.#open(id);if(action==='cancel'){this.#form=undefined;this.#render()}if(action==='delete')void this.#remove(id)};
 #submit=e=>{if(e.target?.matches?.('[data-role="form"]')){e.preventDefault();void this.#save(e.target)}};
 #open(id){this.#form=id?structuredClone(this.#rows.find(x=>x.id===id)):{date:this.#filters.date||todayKey(),time:'08:00',estimatedMinutes:60,status:'Programmato',priority:'Normale',assignedOperatorIds:[]};this.#errors={};this.#render()}
 async #save(form){if(this.#saving)return;let data=readInterventionForm(form);const client=this.#lookups.clients.find(x=>String(x.id)===data.clientId);data={...data,client:client?.name||''};const valid=validateIntervention(data);if(!valid.valid){this.#errors=valid.errors;this.#render();return}this.#saving=true;this.#render();try{if(this.#form.id)await this.#context.services.interventions.updateIntervention(this.#form.id,data);else await this.#context.services.interventions.createIntervention(data);this.#form=undefined;await this.refresh()}catch(e){this.#error=`Intervento non salvato: ${e.message||e}`}finally{this.#saving=false;this.#render()}}
 async #remove(id){if(!id||!globalThis.confirm?.('Eliminare intervento?'))return;try{await this.#context.services.interventions.deleteIntervention(id);await this.refresh()}catch(e){this.#error=`Eliminazione non riuscita: ${e.message||e}`;this.#render()}}
 #render(){if(this.#container)renderInterventions(this.#container,{rows:filterInterventions(this.#rows,this.#filters),filters:this.#filters,form:this.#form,...this.#lookups,saving:this.#saving,error:this.#error,errors:this.#errors})}
 #fail(e){this.#context?.services?.logger?.error?.('[interventions] failure',e);if(this.#container)this.#container.textContent='Modulo Interventi temporaneamente non disponibile'}
}
export const interventionsFeature=new InterventionsFeature();
