import { Events } from '../../../core/events.js'; import { BaseMemoryRepository } from './base-memory-repository.js';
import { normalizeClient,validateClient } from '../../../domain/clients/client.js'; import { normalizeOperator,validateOperator } from '../../../domain/operators/operator.js'; import { normalizeTeam,validateTeam } from '../../../domain/teams/team.js'; import { normalizeVehicle,validateVehicle } from '../../../domain/vehicles/vehicle.js'; import { normalizeIntervention,validateIntervention } from '../../../domain/interventions/intervention.js'; import { normalizeReport,validateReport } from '../../../domain/reports/report.js'; import { normalizeMessage,validateMessage } from '../../../domain/messages/message.js';
const make=(normalize,validate,events,options)=>(config={})=>new BaseMemoryRepository({normalize,validate,events,...options,...config});
export const createClientsMemoryRepository=make(normalizeClient,validateClient,{created:Events.CLIENT_CREATED,updated:Events.CLIENT_UPDATED,deleted:Events.CLIENT_DELETED});
export const createOperatorsMemoryRepository=make(normalizeOperator,validateOperator,{created:Events.OPERATOR_CREATED,updated:Events.OPERATOR_UPDATED});
export const createTeamsMemoryRepository=make(normalizeTeam,validateTeam,{created:Events.TEAM_CREATED,updated:Events.TEAM_UPDATED,deleted:Events.TEAM_DELETED});
export const createVehiclesMemoryRepository=make(normalizeVehicle,validateVehicle,{created:Events.VEHICLE_CREATED,updated:Events.VEHICLE_UPDATED,deleted:Events.VEHICLE_DELETED});
export const createMessagesMemoryRepository=make(normalizeMessage,validateMessage,{created:Events.MESSAGE_CREATED,updated:Events.MESSAGE_UPDATED,deleted:Events.MESSAGE_DELETED});
export function createInterventionsMemoryRepository(config={}){const repo=new BaseMemoryRepository({normalize:normalizeIntervention,validate:validateIntervention,events:{created:Events.INTERVENTION_CREATED,updated:Events.INTERVENTION_UPDATED,deleted:Events.INTERVENTION_DELETED},...config});repo.queryByDate=async date=>(await repo.list()).filter(x=>x.date===date);repo.queryByOperator=async id=>(await repo.list()).filter(x=>x.operatorId===id||x.assignedOperatorIds.includes(id));repo.queryByTeam=async id=>(await repo.list()).filter(x=>x.teamId===id||x.assignedTeamIds.includes(id));return repo;}
export function createReportsMemoryRepository(config={}){const repo=new BaseMemoryRepository({normalize:normalizeReport,validate:validateReport,idField:'interventionId',events:{created:Events.REPORT_CREATED,updated:Events.REPORT_UPDATED},...config});repo.getByInterventionId=id=>repo.getById(id);repo.save=async(id,report)=>(await repo.getById(id))?repo.update(id,report):repo.create({...report,interventionId:id});return repo;}
export function createMemoryRepositories(config={}){return{clients:createClientsMemoryRepository(config),operators:createOperatorsMemoryRepository(config),teams:createTeamsMemoryRepository(config),vehicles:createVehiclesMemoryRepository(config),interventions:createInterventionsMemoryRepository(config),reports:createReportsMemoryRepository(config),messages:createMessagesMemoryRepository(config)}}
