import { EventBus } from '../core/event-bus.js';
import { ErrorBoundary } from '../core/error-boundary.js';
import { createLifecycle } from '../core/lifecycle.js';
import { createLogger } from '../core/logger.js';
import { createEnvironment } from '../config/environment.js';
import { createRepositories } from '../infrastructure/repositories/create-repositories.js';
import { createMemoryAuthAdapter } from '../infrastructure/auth/memory-auth-adapter.js';
import { createNoopRealtimeAdapter } from '../infrastructure/realtime/noop-realtime-adapter.js';
import { AuthService } from '../services/auth/auth-service.js';
import { BackendHealthService } from '../services/backend-health-service.js';
import { GoogleMapsService } from '../services/maps/google-maps-service.js';
import { ClientsService } from '../services/clients/clients-service.js'; import { VehiclesService } from '../services/vehicles/vehicles-service.js'; import { OperatorsService } from '../services/operators/operators-service.js'; import { TeamsService } from '../services/teams/teams-service.js'; import { InterventionsService } from '../services/interventions/interventions-service.js'; import { ReportsService } from '../services/reports/reports-service.js'; import { MessagesService } from '../services/messages/messages-service.js';
import { createAppContext } from './app-context.js'; import { Router } from './router.js'; import { features } from '../features/index.js'; import { renderBootFallback } from './fallback.js';
async function infrastructureFor(environment){if(environment.driver==='memory')return{firebaseClient:null,authAdapter:createMemoryAuthAdapter(),realtime:createNoopRealtimeAdapter()};const[{createFirebaseClient},{createFirebaseAuthAdapter},{createRealtimeAdapter}]=await Promise.all([import('../infrastructure/firebase/firebase-client.js'),import('../infrastructure/firebase/firebase-auth-adapter.js'),import('../infrastructure/firebase/realtime-adapter.js')]);const firebaseClient=createFirebaseClient(environment.firebase);return{firebaseClient,authAdapter:createFirebaseAuthAdapter({auth:firebaseClient.auth,provisionUser:firebaseClient.provisionUser,loadProfile:firebaseClient.loadProfile,deleteProfile:firebaseClient.deleteProfile}),realtime:createRealtimeAdapter({firestore:firebaseClient.firestore})}}
export async function bootstrap(container=document.querySelector('#app'),options={}){if(!container)throw new Error('Bootstrap failed: #app container not found');const logger=options.logger??createLogger(),environment=options.environment??createEnvironment(options.environmentSource??globalThis.__SPURGO_FLOW_ENV__??{}),eventBus=new EventBus({onSubscriberError:(error,event)=>logger.error('Event subscriber failed',{event,error})}),boundary=new ErrorBoundary({onError:(error,details)=>logger.error('Feature failed',{...details,error})}),infra=await infrastructureFor(environment),repositories=createRepositories({driver:environment.driver,eventBus,firebaseClient:infra.firebaseClient,fallbackToMemory:environment.fallbackToMemory,logger});const services={clients:new ClientsService({repository:repositories.clients,eventBus,realtime:infra.realtime}),vehicles:new VehiclesService({repository:repositories.vehicles,eventBus,realtime:infra.realtime}),operators:new OperatorsService({repository:repositories.operators}),teams:new TeamsService({repository:repositories.teams}),interventions:new InterventionsService({repository:repositories.interventions,teamsRepository:repositories.teams,eventBus}),reports:new ReportsService({repository:repositories.reports,eventBus}),messages:new MessagesService({repository:repositories.messages}),auth:new AuthService({adapter:infra.authAdapter}),maps:new GoogleMapsService(environment.googleMaps)};services.backendHealth=new BackendHealthService({driver:environment.driver,auth:services.auth,realtime:infra.realtime});const lifecycle=createLifecycle(),context=createAppContext({eventBus,logger,services,repositories,realtime:infra.realtime,lifecycle});let router;const routeContext={...context,environment,get router(){return router}};router=new Router({routes:features,container,context:routeContext,errorBoundary:boundary,onMountError:feature=>renderBootFallback(container,`${feature.id} temporaneamente non disponibile`)});const onNavigate=event=>{const target=event.target.closest?.('[data-route]');if(!target)return;const interventionId=target.dataset.interventionId;if(interventionId)sessionStorage.setItem('spurgo:selected-intervention',interventionId);router.navigate(target.dataset.route).catch(error=>logger.error('Navigation failed',{error}))};container.addEventListener('click',onNavigate);const initialRoute=options.initialRoute??'login';if(!await router.navigate(initialRoute))throw new Error('Bootstrap failed: initial route was not mounted');return Object.freeze({router,environment,context,close:async()=>{container.removeEventListener('click',onNavigate);lifecycle.abort();await router.destroy();await infra.firebaseClient?.close()}})}
