import assert from 'node:assert/strict';
import { buildAgendaDayModel, buildAgendaWeekModel, computeTimelinePosition, computeTimelineWidth, groupByResource, resourceColor, sortByTime } from '../../../src/features/agenda/agenda.model.js';
import { layoutTimelineLanes } from '../../../src/features/agenda/agenda.timeline.js';
const base={id:'one',date:'2026-08-14',time:'08:00',estimatedMinutes:60,status:'Programmato',priority:'Urgente',client:'Acme',type:'Spurgo'};
assert.equal(buildAgendaDayModel({date:base.date}).interventions.length,0);
const one=buildAgendaDayModel({date:base.date,interventions:[base],operators:[{id:'op',name:'Ada'}]});assert.equal(one.interventions.length,1);assert.equal(one.resources.at(-1).id,'unassigned');
const assigned={...base,id:'assigned',operatorId:'op',assignedOperatorIds:['op']};
const team={...base,id:'team-job',teamId:'red'};
const complete={...assigned,id:'done',time:'09:00',status:'Terminato'};
const missing={...assigned,id:'missing',time:'',estimatedMinutes:null};
const grouped=groupByResource([assigned,team]);assert.equal(grouped.get('operator:op').length,1);assert.equal(grouped.get('team:red').length,1);
assert.deepEqual(sortByTime([complete,assigned]).map(x=>x.id),['assigned','done']);
const model=buildAgendaDayModel({date:base.date,interventions:[assigned,{...assigned,id:'overlap',time:'08:30'},team,complete,missing],operators:[{id:'op',name:'Ada'}],teams:[{id:'red',name:'Rossa'}]});
assert.equal(model.resources.find(x=>x.id==='operator:op').laneCount>=2,true);assert.ok(model.interventions.some(x=>x.status==='Terminato'));assert.ok(model.interventions.some(x=>x.priority==='Urgente'));
assert.equal(buildAgendaWeekModel({date:base.date,interventions:[base]}).days.length,7);
assert.deepEqual(resourceColor('operator:op'),resourceColor('operator:op'));
assert.equal(computeTimelinePosition('08:00'),160);assert.equal(computeTimelinePosition('12:00'),480);assert.equal(computeTimelineWidth(60,0),80);assert.equal(computeTimelineWidth(120,0),160);
assert.ok(computeTimelineWidth(null,1110)>=0);assert.ok(computeTimelineWidth(9999,1100)<=20);assert.equal(layoutTimelineLanes([assigned,{...assigned,id:'b'}])[1].lane,1);
console.log('Agenda empty/day/week/resources/status/priority/fallback and timeline model tests passed');
