import { shell,loading,esc,statusLabel,todayISO } from '../../shared/ui/operational.js';

let root,ctx,view='week',anchor=todayISO(),items=[],teams=[],selectedId=null;
const PALETTE=['#d7e8ff','#dff3e4','#fce6c9','#eadffc','#ffdfe7','#d9f0ee','#fff0bf','#e1e6ff','#f1e0d7','#dcebd2','#f8dcf0','#d9edf8'];
const DAY_NAMES=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];
const MONTHS=['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic'];
const minutes=t=>{const[h,m]=String(t||'00:00').split(':').map(Number);return h*60+m};
const dayKey=d=>{const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)};
const parseDay=value=>new Date(`${value}T12:00:00`);
const addDays=(value,count)=>{const d=parseDay(value);d.setDate(d.getDate()+count);return dayKey(d)};
const monday=value=>{const d=parseDay(value);d.setDate(d.getDate()-((d.getDay()+6)%7));return dayKey(d)};
const teamIds=item=>[...(item.assignedTeamIds??[]),...(item.teamId?[item.teamId]:[])].filter(Boolean);
const teamFor=item=>teams.find(t=>teamIds(item).includes(t.id))??null;
const colorForTeam=id=>{if(!id)return '#e5e9ee';let hash=0;for(const ch of String(id))hash=(hash*31+ch.charCodeAt(0))>>>0;return PALETTE[hash%PALETTE.length]};
const selectedDays=()=>view==='day'?[anchor]:Array.from({length:7},(_,i)=>addDays(monday(anchor),i));
const isToday=d=>d===todayISO();
const titleFor=()=>{if(view==='day'){const d=parseDay(anchor);return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;}const days=selectedDays(),a=parseDay(days[0]),b=parseDay(days[6]);return a.getMonth()===b.getMonth()?`${a.getDate()}–${b.getDate()} ${MONTHS[a.getMonth()]} ${a.getFullYear()}`:`${a.getDate()} ${MONTHS[a.getMonth()]} – ${b.getDate()} ${MONTHS[b.getMonth()]} ${b.getFullYear()}`};
function eventHtml(item){const team=teamFor(item),start=Math.max(0,minutes(item.startTime)-7*60),duration=Math.max(30,Number(item.estimatedMinutes)||60),color=colorForTeam(team?.id),name=item.clientSnapshot?.name||'Cliente';return `<button class="sf-agenda__event ${item.priority==='URGENTE'?'is-urgent':''}" style="--start:${start};--duration:${duration};--team-color:${color}" data-route="intervention-detail" data-intervention-id="${esc(item.id)}" title="${esc(name)}"><span class="sf-agenda__event-time">${esc(item.startTime)} · ${duration} min</span><strong class="sf-agenda__event-title">${esc(name)}</strong><span class="sf-agenda__event-meta">${esc(team?.name||'Senza squadra')} · ${esc(item.type||'Intervento')}</span></button>`}
function detailHtml(){const item=items.find(x=>String(x.id)===String(selectedId));if(!item)return'';const team=teamFor(item);return `<section class="ops-card sf-agenda__detail"><div class="table-title"><div><h2>${esc(item.clientSnapshot?.name||'Cliente')}</h2><small>Dettaglio intervento selezionato</small></div><button class="primary" data-route="intervention-detail" data-intervention-id="${esc(item.id)}">Apri / modifica</button></div><div class="sf-agenda__detail-grid"><div><small>Orario</small><strong>${esc(item.startTime)} · ${Number(item.estimatedMinutes)||60} min</strong></div><div><small>Squadra</small><strong>${esc(team?.name||'Non assegnata')}</strong></div><div><small>Stato</small><strong>${esc(statusLabel(item.status))}</strong></div><div><small>Tipologia</small><strong>${esc(item.type||'—')}</strong></div><div><small>Indirizzo</small><strong>${esc([item.address,item.city].filter(Boolean).join(', ')||'—')}</strong></div><div><small>Priorità</small><strong>${esc(item.priority||'NORMALE')}</strong></div></div></section>`}
function legendHtml(){const active=teams.filter(t=>items.some(i=>teamIds(i).includes(t.id)));const noTeam=items.some(i=>!teamFor(i));return `<div class="sf-agenda__legend">${active.map(t=>`<span class="sf-agenda__legend-item" style="--team-color:${colorForTeam(t.id)}"><i class="sf-agenda__dot"></i>${esc(t.name)}</span>`).join('')}${noTeam?`<span class="sf-agenda__legend-item" style="--team-color:#e5e9ee"><i class="sf-agenda__dot"></i>Senza squadra</span>`:''}</div>`}
function nowLine(day){if(!isToday(day))return'';const now=new Date(),m=now.getHours()*60+now.getMinutes();if(m<420||m>1020)return'';return `<div class="sf-agenda__now" style="top:calc(${m-420}*var(--hour-h)/60)"></div>`}
function render(){if(!root)return;const days=selectedDays();const hours=Array.from({length:10},(_,i)=>7+i);const body=`<section class="ops-card sf-agenda"><div class="sf-agenda__toolbar"><button data-action="prev" aria-label="Periodo precedente">‹</button><button data-action="today">Oggi</button><button data-action="next" aria-label="Periodo successivo">›</button><h2>${esc(titleFor())}</h2><input type="date" data-role="anchor" value="${esc(anchor)}"><button data-view="day" class="${view==='day'?'is-active':''}">Giorno</button><button data-view="week" class="${view==='week'?'is-active':''}">Settimana</button></div>${legendHtml()}<div class="sf-agenda__viewport"><div class="sf-agenda__calendar" data-view="${view}" style="--days:${days.length}"><div class="sf-agenda__corner"></div>${days.map(d=>{const dt=parseDay(d);return `<div class="sf-agenda__day-head ${isToday(d)?'is-today':''}"><small>${DAY_NAMES[(dt.getDay()+6)%7]}</small><strong>${dt.getDate()}</strong></div>`}).join('')}<div class="sf-agenda__time-axis">${hours.map(h=>`<div class="sf-agenda__time-label">${String(h).padStart(2,'0')}:00</div>`).join('')}</div>${days.map(day=>`<div class="sf-agenda__day-column" data-day="${day}"><span class="sf-agenda__lunch-label">Pausa 12–13</span>${nowLine(day)}${items.filter(x=>x.date===day&&x.status!=='ANNULLATO').map(eventHtml).join('')}</div>`).join('')}</div></div></section>${detailHtml()}`;root.innerHTML=shell('Agenda',body,'agenda');}
async function refresh(){const [newItems,newTeams]=await Promise.all([ctx.services.interventions.listInterventions(),ctx.services.teams.listTeams()]);items=newItems;teams=newTeams;render();}
function click(event){const eventButton=event.target.closest?.('[data-intervention-id]');if(eventButton){selectedId=eventButton.dataset.interventionId;return;}const action=event.target.closest?.('[data-action]')?.dataset.action;if(action==='today'){anchor=todayISO();render();return;}if(action==='prev'){anchor=addDays(anchor,view==='day'?-1:-7);render();return;}if(action==='next'){anchor=addDays(anchor,view==='day'?1:7);render();return;}const nextView=event.target.closest?.('[data-view]')?.dataset.view;if(nextView==='day'||nextView==='week'){view=nextView;render();}}
function change(event){if(event.target.matches?.('[data-role="anchor"]')&&event.target.value){anchor=event.target.value;render();}}
export const agendaFeature=Object.freeze({id:'agenda',async mount(container,context){root=container;ctx=context;root.innerHTML=loading('Agenda');root.addEventListener('click',click);root.addEventListener('change',change);context.lifecycle?.add(context.eventBus.on('intervention:created',refresh));context.lifecycle?.add(context.eventBus.on('intervention:updated',refresh));context.lifecycle?.add(context.eventBus.on('intervention:statusChanged',refresh));context.lifecycle?.add(context.eventBus.on('intervention:assignmentChanged',refresh));await refresh();},unmount(){root?.removeEventListener('click',click);root?.removeEventListener('change',change);root=ctx=undefined;items=[];teams=[];selectedId=null;view='week';anchor=todayISO();}});
