import test from 'node:test'; import assert from 'node:assert/strict'; import { EventBus } from '../../src/core/event-bus.js'; import { Events } from '../../src/core/events.js'; import { createMemoryRepositories } from '../../src/infrastructure/repositories/memory/index.js'; import { InterventionsService } from '../../src/services/interventions/interventions-service.js'; import { ReportsService } from '../../src/services/reports/reports-service.js'; import { InterventionStatus } from '../../src/domain/interventions/constants.js';
const ts='2026-08-14T10:00:00.000Z';
const fixtures={clients:{id:'c1',name:'Client',active:true,createdAt:ts,updatedAt:ts},operators:{id:'o1',username:'op',name:'Ada',active:true,createdAt:ts,updatedAt:ts},teams:{id:'t1',name:'Team',operatorIds:['o1'],active:true,createdAt:ts,updatedAt:ts},vehicles:{id:'v1',plate:'AA000AA',active:true,createdAt:ts,updatedAt:ts},interventions:{id:'i1',clientId:'c1',address:'Via Roma',coordinates:{latitude:45,longitude:9},date:'2026-08-14',startTime:'10:00',estimatedMinutes:60,type:'SPURGO',priority:'NORMALE',status:'PROGRAMMATO',assignedOperatorIds:['o1'],assignedTeamIds:[],createdAt:ts,updatedAt:ts},reports:{interventionId:'i1',activities:[],anomalies:[],materials:[],photos:[],createdAt:ts,updatedAt:ts},messages:{id:'m1',senderId:'o1',senderType:'operator',recipientId:'c1',recipientType:'client',text:'Ciao',createdAt:ts}};
for(const name of Object.keys(fixtures))test(`${name} memory CRUD, copy safety and identity errors`,async()=>{const repo=createMemoryRepositories()[name],record=fixtures[name],id=record.id??record.interventionId;await repo.create(record);assert.equal((await repo.list()).length,1);const copy=await repo.getById(id);copy.active=false;assert.notEqual((await repo.getById(id)).active,false);await repo.update(id,{notes:'x'});assert.equal((await repo.getById(id)).notes,'x');await assert.rejects(repo.create(record),/Duplicate/);await assert.rejects(repo.update('missing',{notes:'x'}),/Missing/);await assert.rejects(repo.remove('missing'),/Missing/);await repo.remove(id);assert.equal(await repo.getById(id),null);});
test('intervention semantic merge preserves nested data and replaces arrays',async()=>{const repo=createMemoryRepositories().interventions;await repo.create(fixtures.interventions);await repo.update('i1',{notes:'x',coordinates:{latitude:46}});const value=await repo.getById('i1');assert.deepEqual(value.coordinates,{latitude:46,longitude:9});assert.deepEqual(value.assignedOperatorIds,['o1']);assert.equal('reportData' in value,false);await repo.update('i1',{assignedOperatorIds:['o2']});assert.deepEqual((await repo.getById('i1')).assignedOperatorIds,['o2']);});
test('protected intervention fields fail while semantic completion succeeds',async()=>{const repo=createMemoryRepositories().interventions;await repo.create(fixtures.interventions);const service=new InterventionsService({repository:repo,clock:()=>ts,idFactory:()=> 'new'});await assert.rejects(service.updateIntervention('i1',{status:'TERMINATO'}),/Protected/);await service.startIntervention('i1');await service.completeIntervention('i1');assert.equal((await repo.getById('i1')).status,InterventionStatus.TERMINATO);});
test('report service never changes intervention lifecycle fields',async()=>{const repositories=createMemoryRepositories();await repositories.interventions.create(fixtures.interventions);const before=await repositories.interventions.getById('i1');await new ReportsService({repository:repositories.reports,clock:()=>ts}).saveReport('i1',{activities:['done']});const after=await repositories.interventions.getById('i1');assert.equal(after.status,before.status);assert.equal(after.actualStart,before.actualStart);assert.equal(after.actualEnd,before.actualEnd);});
test('repository emits only after successful writes',async()=>{const order=[],bus=new EventBus();bus.on(Events.CLIENT_CREATED,async payload=>{order.push((await repo.getById(payload.entityId))?'persisted':'missing')});const repo=createMemoryRepositories({eventBus:bus}).clients;await assert.rejects(repo.create({...fixtures.clients,name:''}));assert.deepEqual(order,[]);await repo.create(fixtures.clients);await new Promise(resolve=>setTimeout(resolve,0));assert.deepEqual(order,['persisted']);});

test('Report is an optional isolated aggregate with ReportsRepository as its only store',async()=>{const repositories=createMemoryRepositories();await repositories.interventions.create(fixtures.interventions);assert.equal(await repositories.reports.getByInterventionId('i1'),null);const before=await repositories.interventions.getById('i1');await repositories.reports.save('i1',fixtures.reports);await repositories.reports.update('i1',{relation:'completed',materials:[{name:'sale'}]});assert.equal('reportData' in before,false);assert.equal((await repositories.reports.getByInterventionId('i1')).relation,'completed');assert.deepEqual(await repositories.interventions.getById('i1'),before);});

test('Intervention rejects Report-owned fields',async()=>{const repo=createMemoryRepositories().interventions;for(const field of ['relation','signatures','photos','materials','reportData'])await assert.rejects(repo.create({...fixtures.interventions,id:`bad-${field}`,[field]:[]}),/belongs to Report/);});

test('create rejects every domain-controlled field before persistence',async()=>{const repo=createMemoryRepositories().interventions;const service=new InterventionsService({repository:repo,clock:()=>ts,idFactory:()=>'generated'});await assert.rejects(service.createIntervention({clientId:'c1',address:'Via Roma',date:'2026-08-14',startTime:'10:00',estimatedMinutes:60,type:'SPURGO',id:'HACK',status:'TERMINATO',actualEnd:ts,assignedOperatorIds:['x']}),/Domain-controlled.*id.*status.*actualEnd.*assignedOperatorIds/);assert.deepEqual(await repo.list(),[]);const created=await service.createIntervention({clientId:'c1',address:'Via Roma',date:'2026-08-14',startTime:'10:00',estimatedMinutes:60,type:'SPURGO',unknown:'discarded'});assert.equal(created.id,'generated');assert.equal(created.status,'PROGRAMMATO');assert.equal('unknown' in created,false);});

test('identity is immutable for Intervention and Report updates',async()=>{const repositories=createMemoryRepositories();await repositories.interventions.create(fixtures.interventions);await repositories.reports.save('i1',fixtures.reports);await assert.rejects(repositories.interventions.update('i1',{id:'NEW'}),/immutable/);await assert.rejects(repositories.reports.update('i1',{interventionId:'NEW'}),/immutable/);});

test('status matrix guards commands and preserves actualStart across reopen',async()=>{const repo=createMemoryRepositories().interventions;const ticks=['2026-08-14T10:01:00.000Z','2026-08-14T10:02:00.000Z','2026-08-14T10:03:00.000Z','2026-08-14T10:04:00.000Z'];const service=new InterventionsService({repository:repo,clock:()=>ticks.shift()??ts});await repo.create(fixtures.interventions);await assert.rejects(service.completeIntervention('i1'),/PROGRAMMATO -> TERMINATO/);await assert.rejects(service.reopenIntervention('i1'),/PROGRAMMATO -> RIAPERTO/);await service.startIntervention('i1');const started=(await repo.getById('i1')).actualStart;await service.completeIntervention('i1');await service.reopenIntervention('i1');await service.startIntervention('i1');assert.equal((await repo.getById('i1')).actualStart,started);const cancelled={...fixtures.interventions,id:'cancelled',status:'ANNULLATO'};await repo.create(cancelled);await assert.rejects(service.startIntervention('cancelled'),/ANNULLATO -> IN_CORSO/);});

test('completion emits one persistence event then one statusChanged and one completed event',async()=>{const seen=[],bus=new EventBus();for(const type of [Events.INTERVENTION_UPDATED,Events.INTERVENTION_STATUS_CHANGED,Events.INTERVENTION_COMPLETED])bus.on(type,()=>seen.push(type));const repo=createMemoryRepositories({eventBus:bus}).interventions;await repo.create({...fixtures.interventions,status:'IN_CORSO',actualStart:ts});await new InterventionsService({repository:repo,eventBus:bus,clock:()=>ts}).completeIntervention('i1');await new Promise(resolve=>setTimeout(resolve,0));assert.deepEqual(seen,[Events.INTERVENTION_UPDATED,Events.INTERVENTION_STATUS_CHANGED,Events.INTERVENTION_COMPLETED]);});
