import test from 'node:test'; import assert from 'node:assert/strict';
import { readEnvironment } from '../../src/config/environment.js';
import { AuthService, normalizeUsername, userEmail } from '../../src/services/auth/auth-service.js';
import { AuthError, mapAuthError, mapRepositoryError, RepositoryError } from '../../src/infrastructure/firebase/errors.js';
import { createRealtimeAdapter } from '../../src/infrastructure/firebase/realtime-adapter.js';

const config={apiKey:'test-key',authDomain:'test.firebaseapp.com',projectId:'test-project',appId:'1:test:web:test'};
test('environment defaults to memory but accepts explicit production Firebase configuration',()=>{assert.equal(readEnvironment().driver,'memory');const env=readEnvironment({driver:'firebase',firebase:config});assert.equal(env.driver,'firebase');assert.equal(env.firebase.useEmulator,false);assert.equal(env.firebase.projectId,'test-project');});
test('emulator configuration still validates emulator-only fields',()=>{assert.throws(()=>readEnvironment({driver:'firebase',firebase:{...config,useEmulator:true}}),/emulator configuration is missing/);});
test('AuthService preserves Spurgo Flow usernames and validates role',async()=>{const calls=[];const adapter={login:async(...v)=>(calls.push(v),{uid:'u1',role:'operator',operatorId:'u1',active:true}),logout:async()=>{},currentIdentity:()=>null,onAuthChanged:()=>()=>{},createTestAccount:async(...v)=>(calls.push(v),{uid:'u2',email:v[0],role:'operator',operatorId:'u2'})};const service=new AuthService({adapter});assert.equal(normalizeUsername(' Ada '),'ada');assert.equal(userEmail(' Ada '),'ada@spurgoflow.app');const identity=await service.loginOperator(' ADA ','pw');assert.deepEqual(calls[0],['ada@spurgoflow.app','pw']);assert.equal(identity.operatorId,'u1');assert.equal(service.currentIdentity().uid,'u1');await service.createOperatorAccount('Luca','abcdef');assert.equal(calls[1][0],'luca@spurgoflow.app');assert.equal(calls[1][2].role,'operator');});
test('Firebase errors are mapped to stable boundary errors',()=>{const auth=mapAuthError({code:'auth/invalid-credential'});assert.ok(auth instanceof AuthError);assert.equal(auth.code,'INVALID_CREDENTIALS');const repository=mapRepositoryError({code:'unavailable'});assert.ok(repository instanceof RepositoryError);assert.equal(repository.code,'DATA_UNAVAILABLE');});
test('realtime subscriptions are read-only, replace duplicates, and unsubscribe idempotently',()=>{let active=0,stopped=0;const subscribe=(_name,next)=>{active++;next({docs:[{data:()=>({id:'i1'})}]});return()=>{active--;stopped++;};};const realtime=createRealtimeAdapter({subscribe});const events=[];const callback=event=>events.push(event);const first=realtime.subscribeCollection('interventions',callback,'screen');const second=realtime.subscribeCollection('interventions',callback,'screen');assert.equal(active,1);assert.equal(stopped,1);assert.equal(realtime.activeSubscriptionCount(),1);assert.equal(events[0].readOnly,true);first();second();second();assert.equal(active,0);assert.equal(stopped,2);assert.equal(realtime.activeSubscriptionCount(),0);});
