import test from 'node:test'; import assert from 'node:assert/strict';
import { readEnvironment } from '../../src/config/environment.js';
import { AuthService, normalizeUsername, operatorTestEmail } from '../../src/services/auth/auth-service.js';
import { AuthError, mapAuthError, mapRepositoryError, RepositoryError } from '../../src/infrastructure/firebase/errors.js';
import { PRODUCTION_DISABLED, createFirebaseClient } from '../../src/infrastructure/firebase/firebase-client.js';
import { createRealtimeAdapter } from '../../src/infrastructure/firebase/realtime-adapter.js';

test('environment defaults to memory and requires explicit emulator configuration',()=>{assert.equal(readEnvironment().driver,'memory');assert.throws(()=>readEnvironment({driver:'firebase-emulator'}),/configuration is missing/);});
test('Firebase production guard runs before SDK initialization',()=>{assert.throws(()=>createFirebaseClient({useEmulator:false}),new RegExp(PRODUCTION_DISABLED));});
test('AuthService normalizes usernames and knows only its adapter port',async()=>{const calls=[];const adapter={login:async(...v)=>(calls.push(v),{uid:'u1'}),logout:async()=>{},currentIdentity:()=>null,onAuthChanged:()=>()=>{},createTestAccount:async(...v)=>(calls.push(v),{uid:'u1'})};const service=new AuthService({adapter});assert.equal(normalizeUsername(' Ada '),'ada');assert.equal(operatorTestEmail(' Ada '),'ada@operator.spurgoflow.test');await service.loginOperator(' ADA ','pw');assert.deepEqual(calls[0],['ada@operator.spurgoflow.test','pw']);assert.equal(service.currentIdentity(),null);assert.equal(typeof service.onAuthChanged(()=>{}),'function');});
test('Firebase errors are mapped to stable boundary errors',()=>{const auth=mapAuthError({code:'auth/invalid-credential'});assert.ok(auth instanceof AuthError);assert.equal(auth.code,'INVALID_CREDENTIALS');const repository=mapRepositoryError({code:'unavailable'});assert.ok(repository instanceof RepositoryError);assert.equal(repository.code,'DATA_UNAVAILABLE');});
test('realtime subscriptions are read-only, replace duplicates, and unsubscribe idempotently',()=>{let active=0,stopped=0;const subscribe=(_name,next)=>{active++;next({docs:[{data:()=>({id:'i1'})}]});return()=>{active--;stopped++;};};const realtime=createRealtimeAdapter({subscribe});const events=[];const callback=event=>events.push(event);const first=realtime.subscribeCollection('interventions',callback,'screen');const second=realtime.subscribeCollection('interventions',callback,'screen');assert.equal(active,1);assert.equal(stopped,1);assert.equal(realtime.activeSubscriptionCount(),1);assert.equal(events[0].readOnly,true);first();second();second();assert.equal(active,0);assert.equal(stopped,2);assert.equal(realtime.activeSubscriptionCount(),0);});
