import test from 'node:test'; import assert from 'node:assert/strict';
import { createFirebaseClient } from '../../src/infrastructure/firebase/firebase-client.js';
import { createFirebaseRepositories } from '../../src/infrastructure/firebase/firebase-repositories/index.js';
import { AuthService } from '../../src/services/auth/auth-service.js';
import { createFirebaseAuthAdapter } from '../../src/infrastructure/firebase/firebase-auth-adapter.js';

const enabled=process.env.FIREBASE_EMULATOR_RUN==='1';
const config={host:'127.0.0.1',firestorePort:8080,authPort:9099,projectId:'spurgoflow-v8-alpha3-test',apiKey:'demo-test-only',useEmulator:true};
test('Firestore/Auth emulator integration (set FIREBASE_EMULATOR_RUN=1)',{skip:!enabled},async()=>{const client=createFirebaseClient(config);try{const repositories=createFirebaseRepositories({client});const id=`i-${Date.now()}`;const intervention={id,clientId:'c1',address:'Via Test',coordinates:{latitude:45,longitude:9},date:'2026-08-14',startTime:'10:00',estimatedMinutes:60,type:'SPURGO',priority:'NORMALE',status:'PROGRAMMATO',assignedOperatorIds:['o1'],assignedTeamIds:[]};await repositories.interventions.create(intervention);const updated=await repositories.interventions.update(id,{notes:'ok',coordinates:{latitude:46}});assert.equal(updated.id,id);assert.deepEqual(updated.coordinates,{latitude:46,longitude:9});assert.deepEqual(updated.assignedOperatorIds,['o1']);const auth=new AuthService({adapter:createFirebaseAuthAdapter({auth:client.auth,useEmulator:true})});const username=`operator-${Date.now()}`;await auth.createTestOperatorAccount(username,'test-password-123');await auth.logout();assert.equal(auth.currentIdentity(),null);assert.equal((await auth.loginOperator(username,'test-password-123')).email,`${username}@operator.spurgoflow.test`);await auth.logout();await assert.rejects(auth.loginOperator(username,'wrong-password'),error=>error.code==='INVALID_CREDENTIALS');await repositories.interventions.remove(id);}finally{await client.close();}});
